- name: Ensure Java runtime is installed
  apt:
    name: default-jre
    state: present
  when: ansible_os_family == 'Debian'

- name: Download Tomcat archive
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/tmp/tomcat-{{ tomcat_version }}.tar.gz"

- name: Extract Tomcat
  unarchive:
    src: "/tmp/tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes

- name: Configure systemd service for Tomcat
  copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Apache Tomcat
      After=network.target
      
      [Service]
      Type=forking
      ExecStart={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
      ExecStop={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/shutdown.sh
      User={{ tomcat_user }}
      Group={{ tomcat_group }}
      
      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes
  notify: start tomcat