- name: Open bastion tunnel and verify backend connection
  hosts: localhost
  gather_facts: false
  vars:
    bastion_name: schedule-bastion
    resource_group: class-schedule-rg
    vm_name: schedule-backend
    admin_username: azureuser
    ssh_key_path: ~/.ssh/vagrant_id_ed25519
    local_port: 50022
  tasks:
    - name: Start Bastion tunnel (persistent)
      shell: |
        az network bastion tunnel \
          --name {{ bastion_name }} \
          --resource-group {{ resource_group }} \
          --target-resource-id $(az vm show -g {{ resource_group }} -n {{ vm_name }} --query id -o tsv) \
          --resource-port 22 \
          --port {{ local_port }} \
          --timeout 3600
      async: 3605
      poll: 0

    - name: Pause a few seconds for tunnel
      pause:
        seconds: 5

- name: Verify backend connectivity
  hosts: backend
  gather_facts: false
  tasks:
    - name: Test connectivity
      ansible.builtin.ping:

    - name: Показати hostname і приватні IP-адреси
      ansible.builtin.shell: |
        echo "HOSTNAME: $(hostname)"
        echo "IP LIST:"
        ip -4 -o a show scope global | awk '{print " - "$2" "$4}'
      register: hostinfo

    - name: Вивести інформацію про хост
      debug:
        var: hostinfo.stdout
